# ======================
# Netlify Configuration
# ======================

# Permanent Redirects (301)
[[redirects]]
  from = "/startup"
  to = "/vision"
  status = 301
  force = true

[[redirects]]
  from = "/films"
  to = "/cinema"
  status = 301
  force = true

[[redirects]]
  from = "/projects"
  to = "/portfolio"
  status = 301
  force = true

[[redirects]]
  from = "/cv"
  to = "/CV_Olexander_Tsiomakh_Frontend.pdf"
  status = 301
  force = true

# Single Page Application (SPA) Routing (200)
[[redirects]]
  from = "/ua/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ru/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.youtube.com https://s.ytimg.com https://i.ytimg.com https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' https: data:; media-src 'self' https: blob:; connect-src 'self' https://www.google-analytics.com; frame-src https://www.youtube.com https://www.youtube-nocookie.com; object-src 'none'; base-uri 'self'; form-action 'self';"