# Redirect all recognized crawlers to Prerender
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/https://buhowski.dev/:splat"
  status = 200
  force = true
  priority = 1
  conditions = { UserAgent = [
    "googlebot",
    "bingbot",
    "yandex",
    "baiduspider",
    "duckduckbot",
    "slurp",
    "sogou",
    "exabot",
    "facebot",
    "ia_archiver",
    "facebookexternalhit",
    "twitterbot",
    "linkedinbot",
    "instagram",
    "pinterest",
    "slackbot",
    "discordbot",
    "skypeuripreview",
    "whatsapp",
    "telegrambot",
    "applebot",
    "vkShare",
    "redditbot"
  ] }

# SPA redirect for all other users
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200