[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/https://buhowski.dev/:splat"
  status = 200
  force = true
  query = {user-agent = "(googlebot|bingbot|yandex|baiduspider|facebookexternalhit|twitterbot|slackbot|discordbot|telegrambot|linkedinbot)"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
