# Permanent redirects
[[redirects]]
  from = "/startup"
  to = "/vision"
  status = 301
  force = true

[[redirects]]
  from = "/films"
  to = "/cinema"
  status = 301
  force = true

[[redirects]]
  from = "/projects"
  to = "/portfolio"
  status = 301
  force = true

[[redirects]]
  from = "/cv"
  to = "/CV_Olexander_Tsiomakh_Frontend.pdf"
  status = 301
  force = true

# Explicit SPA rules for language-prefixed URLs
[[redirects]]
  from = "/ua/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ru/*"
  to = "/index.html"
  status = 200

# Catch-all for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
